### ISSUE TITLE
Platform compatibility issue with AnVILGCP

### ISSUE THREAD

**Issue by shbrief** [shbrief/AnVILWorkflow#21]
@LiNk-NY 

Do AnVILGCP functions work only within the AnVIL platform?
I'm getting the following error from the `cloneWorkspace` function.

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'platform' in selecting a method for function 'avworkspace_clone': The runtime environment must be within an AnVIL workspace.
```

**Comment by LiNk-NY** [comment]
For GCP, it works outside of Anvil with the right environment variables set: 

https://github.com/Bioconductor/AnVILBase/blob/devel/R%2Fcloud_platform.R#L17

**Comment by shbrief** [comment]
What should be the input for a non-cloud environment (i.e., neither AnVILGCP or AnVILAz)?

**Comment by LiNk-NY** [comment]
It is based on your environment variables / options so you should have either the `GOOGLE_PROJECT` environment variable or an `GCLOUD_SDK_PATH` option set.

**Comment by LiNk-NY** [comment]
Hi @shbrief 
Were you able to resolve this issue?

**Comment by shbrief** [comment]
Yes. Thanks!
