### ISSUE TITLE
update devel branch in Bioconductor

### ISSUE THREAD

**Issue by LiNk-NY** [shbrief/AnVILWorkflow#22]
@shbrief 
The package is in an error state on Bioconductor devel: 
https://bioconductor.org/packages/devel/bioc/html/AnVILWorkflow.html

Can you push updates to the Bioconductor `devel` branch? 

Thanks!

**Comment by shbrief** [comment]
Thanks for letting me know.
Unfortunately, I don’t have access to my computer this week. I’ll check this issue once I’m back next week. Sorry for the delay.

On Aug 5, 2024, at 4:27 PM, Marcel Ramos Pérez ***@***.***> wrote:

﻿

@shbrief<https://github.com/shbrief>
The package is in an error state on Bioconductor devel:
https://bioconductor.org/packages/devel/bioc/html/AnVILWorkflow.html

Can you push updates to the Bioconductor devel branch?

Thanks!
